// <auto-generated />
using System;
using MaaltijdApplicatie.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaaltijdApplicatie.Migrations
{
    [DbContext(typeof(AppDomainDbContext))]
    [Migration("20180920184807_Added domain database")]
    partial class Addeddomaindatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MaaltijdApplicatie.Models.Domain.Guest", b =>
                {
                    b.Property<int>("MealId");

                    b.Property<int>("StudentId");

                    b.HasKey("MealId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("MaaltijdApplicatie.Models.Domain.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CookId");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int?>("MaxGuests")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal?>("Price")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CookId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("MaaltijdApplicatie.Models.Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MaaltijdApplicatie.Models.Domain.Guest", b =>
                {
                    b.HasOne("MaaltijdApplicatie.Models.Domain.Meal", "Meal")
                        .WithMany("Guests")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MaaltijdApplicatie.Models.Domain.Student", "Student")
                        .WithMany("GuestOfMeals")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MaaltijdApplicatie.Models.Domain.Meal", b =>
                {
                    b.HasOne("MaaltijdApplicatie.Models.Domain.Student", "Cook")
                        .WithMany("CookOfMeals")
                        .HasForeignKey("CookId");
                });
#pragma warning restore 612, 618
        }
    }
}
